### ISSUE TITLE
Using {linne} inside a shiny module

### ISSUE THREAD

**Issue by shahreyar-abeer** [JohnCoene/linne#3]
Hi John,

Could you please add an example of using {linne} inside a shiny module?

Thanks.

**Comment by JohnCoene** [comment]
Gah, I had not thought of modules! Let me see if I can cobble something together.

**Comment by JohnCoene** [comment]
I pushed a poor temporary "fix" to enable this; not very elegant. I'll come up with something better eventually.

```r
sel_id("elementId", ns = "myNamespace")
```

Pass the namespace to `sel_id`; that's the only place where it is needed

**Comment by shahreyar-abeer** [comment]
Great!
Thanks for that.
I guess it will work for now.
